name: Push Image

on:
  - push
  - pull_request

env:
  GCP_PROJECT_ID: college-app-366823
  GCP_REGION: asia-northeast1
  IMAGE: gcr.io/college-app-366823/csap
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  INSTANCE_CONNECTION_NAME: college-app-366823:asia-northeast1:college-app

jobs:
  push:
    # Add "id-token" with the intended permissions.
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: "${{ secrets.WIF_PROVIDER }}"
          service_account: "${{ secrets.WIF_SERVICE_ACCOUNT }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - run: gcloud auth login

      - name: "Configure docker to use the gcloud cli"
        run: gcloud auth configure-docker --quiet

      - name: "Build a docker image"
        run: docker build -t $IMAGE .

      - name: "Push the docker image to Container Registry"
        run: docker push $IMAGE
